In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"groceery - Form Responses 1.csv")

In [3]:
df.head()

,Timestamp,Email Address,Your Name,Age,How often do you typically go grocery shopping?,Do you prefer shopping online or in-store?,What types of fruits do you enjoy?,What types of vegetables do you enjoy?,What is your average budget for a grocery shopping trip?,Are you interested in healthier food options?,Any specific health goals or preferences?,Do you have preferred brands for certain products?,What is your preferred payment method for grocery shopping?,Do you have any specific allergy w.r.to fruits or vegetables (If not write NA)
0,1/11/2024 17:44:09,kokanevedant7@gmail.com,Vedant,18-24,Once a week,Online,Apple,Carrots,200,Yes,muscle gain,Yes,Credit Card,NaN
1,1/11/2024 17:49:13,kalpak9370@gmail.com,Kalpak,18-24,Once a week,in-store,Banana,Broccoli,100,Yes,muscle gain,No,Mobile Wallet,NaN
2,1/11/2024 17:50:48,pranitaraut2002@gmail.com,Pranita,18-24,twice a month,Online,Orange,Carrots,1000,Yes,Weight loss,Yes,Mobile Wallet,NaN
3,1/11/2024 17:51:23,pranitaraut2002@gmail.com,Pranita,18-24,twice a month,Online,Apple,Carrots,1000,Yes,Weight loss,Yes,Cash,NaN
4,1/11/2024 18:11:29,muskanhannure@gmail.com,Muskan Hannure,18-24,Once a week,in-store,Mango,Green vegetable,50,Yes,Maintain current health,Sometimes,Mobile Wallet,NaN

In [4]:
df = df.rename(columns = {'How often do you typically go grocery shopping?':'Shopping Frequency','Do you prefer shopping online or in-store': 'Shopping Mode','What types of fruits do you enjoy?':'Prefered Fruits','What types of vegetables do you enjoy?':'Prefered vegetables','What is your average budget for a grocery shopping trip?':'Budget','Are you interested in healthier food options?':'Healthier Food Options','Any specific health goals or preferences?':'Health Goals','Do you have preferred brands for certain products?':'Preferred Brands','What is your preferred payment method for grocery shopping?':'Payment Mode','Do you have any specific allergy w.r.to fruits or vegetables (If not write NA)':'Allergy'})

In [5]:
df.head()

,Timestamp,Email Address,Your Name,Age,Shopping Frequency,Do you prefer shopping online or in-store?,Prefered Fruits,Prefered vegetables,Budget,Are you interested in healthier food options?,Health Goals,Do you have preferred brands for certain products?,Payment Mode,Allergy
0,1/11/2024 17:44:09,kokanevedant7@gmail.com,Vedant,18-24,Once a week,Online,Apple,Carrots,200,Yes,muscle gain,Yes,Credit Card,NaN
1,1/11/2024 17:49:13,kalpak9370@gmail.com,Kalpak,18-24,Once a week,in-store,Banana,Broccoli,100,Yes,muscle gain,No,Mobile Wallet,NaN
2,1/11/2024 17:50:48,pranitaraut2002@gmail.com,Pranita,18-24,twice a month,Online,Orange,Carrots,1000,Yes,Weight loss,Yes,Mobile Wallet,NaN
3,1/11/2024 17:51:23,pranitaraut2002@gmail.com,Pranita,18-24,twice a month,Online,Apple,Carrots,1000,Yes,Weight loss,Yes,Cash,NaN
4,1/11/2024 18:11:29,muskanhannure@gmail.com,Muskan Hannure,18-24,Once a week,in-store,Mango,Green vegetable,50,Yes,Maintain current health,Sometimes,Mobile Wallet,NaN

In [6]:
df['Age'].unique()

array(['18-24', '25-34', '35-44', '55+', '23', '22', '21', '20', '24',
       '55', '40', '44', '33', '43', '36', '37', '27', '34', '25', '45',
       '56', '19', '67', '41'], dtype=object)

In [7]:
df['Age']=df['Age'].replace('18-24','18')
df['Age']=df['Age'].replace('25-34','25')
df['Age']=df['Age'].replace('35-44','35')
df['Age']=df['Age'].replace('55+','55')

In [8]:
df['Age'].unique()

array(['18', '25', '35', '55', '23', '22', '21', '20', '24', '40', '44',
       '33', '43', '36', '37', '27', '34', '45', '56', '19', '67', '41'],
      dtype=object)

In [9]:
df.head()

,Timestamp,Email Address,Your Name,Age,Shopping Frequency,Do you prefer shopping online or in-store?,Prefered Fruits,Prefered vegetables,Budget,Are you interested in healthier food options?,Health Goals,Do you have preferred brands for certain products?,Payment Mode,Allergy
0,1/11/2024 17:44:09,kokanevedant7@gmail.com,Vedant,18,Once a week,Online,Apple,Carrots,200,Yes,muscle gain,Yes,Credit Card,NaN
1,1/11/2024 17:49:13,kalpak9370@gmail.com,Kalpak,18,Once a week,in-store,Banana,Broccoli,100,Yes,muscle gain,No,Mobile Wallet,NaN
2,1/11/2024 17:50:48,pranitaraut2002@gmail.com,Pranita,18,twice a month,Online,Orange,Carrots,1000,Yes,Weight loss,Yes,Mobile Wallet,NaN
3,1/11/2024 17:51:23,pranitaraut2002@gmail.com,Pranita,18,twice a month,Online,Apple,Carrots,1000,Yes,Weight loss,Yes,Cash,NaN
4,1/11/2024 18:11:29,muskanhannure@gmail.com,Muskan Hannure,18,Once a week,in-store,Mango,Green vegetable,50,Yes,Maintain current health,Sometimes,Mobile Wallet,NaN

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 14 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Timestamp                                            52 non-null     object
 1   Email Address                                        14 non-null     object
 2   Your Name                                            52 non-null     object
 3   Age                                                  52 non-null     object
 4   Shopping Frequency                                   52 non-null     object
 5   Do you prefer shopping online or in-store?           52 non-null     object
 6   Prefered Fruits                                      52 non-null     object
 7   Prefered vegetables                                  52 non-null     object
 8   Budget                                               52 non-null     object
 9   Are you interested in healthier food options?        52 non-null     object
 10  Health Goals                                         51 non-null     object
 11  Do you have preferred brands for certain products?   14 non-null     object
 12  Payment Mode                                         52 non-null     object
 13  Allergy                                              3 non-null      object
dtypes: object(14)
memory usage: 5.8+ KB

In [11]:
df['Prefered Fruits'].unique()

array(['Apple', 'Banana', 'Orange', 'Mango', 'All seasonal fruits .',
       'Pineapple', 'Grape', 'Cheeries',
       'Apple, Banana, Lemon, Pomegranate(डाळिंब/अनार)',
       'Apple, Banana, Orange, Lemon, Pomegranate(डाळिंब/अनार), Guava(पेरु), Custard apple(सीताफल), ',
       'Apple, Banana, Orange, Pomegranate(डाळिंब/अनार), Guava(पेरु), Custard apple(सीताफल), Sapodilla,',
       'Apple, Banana, Orange, Lemon, Pomegranate(डाळिंब/अनार), Guava(पेरु)',
       'Apple, Banana, Lemon, Guava(पेरु)',
       'Apple, Banana, Orange, Lemon, Pomegranate(डाळिंब/अनार), Guava(पेरु), Custard apple(सीताफल)',
       'Banana, Lemon',
       'Apple, Banana, Lemon, Guava(पेरु), Kiwi, strawberry ',
       'Apple, Banana, Orange, Pomegranate(डाळिंब/अनार)',
       'Apple, Banana, Orange, Lemon, Pomegranate(डाळिंब/अनार), Custard apple(सीताफल)',
       'Orange, Pomegranate(डाळिंब/अनार), Custard apple(सीताफल)',
       'Lemon, Pomegranate(डाळिंब/अनार), Guava(पेरु), Custard apple(सीताफल)',
       'Apple, Banana, Orange, Lemon, Pomegranate(डाळिंब/अनार)',
       'Orange, Lemon, Pomegranate(डाळिंब/अनार)',
       'Apple, Banana, Orange, Lemon',
       'Orange, Pomegranate(डाळिंब/अनार), Guava(पेरु)',
       'Banana, Pomegranate(डाळिंब/अनार), Custard apple(सीताफल)',
       'Orange, Lemon, Guava(पेरु)',
       'Apple, Banana, Orange, Guava(पेरु), Custard apple(सीताफल)',
       'Banana, Orange, Lemon',
       'Orange, Lemon, Pomegranate(डाळिंब/अनार), Guava(पेरु), Custard apple(सीताफल)',
       'Pomegranate(डाळिंब/अनार)', 'Apple, Banana, Orange',
       'Banana, Orange, Lemon, Pomegranate(डाळिंब/अनार)',
       'Apple, Orange, Pomegranate(डाळिंब/अनार), Custard apple(सीताफल)',
       'Lemon, Pomegranate(डाळिंब/अनार), Custard apple(सीताफल)',
       'Banana, Orange',
       'Orange, Lemon, Pomegranate(डाळिंब/अनार), Strawbeery'],
      dtype=object)

In [12]:
import re
df['Prefered Fruits'] = df['Prefered Fruits'].str.replace(r'Pomegranate\(डाळिंब/अनार\)', 'Pomegranate', regex=True)
df['Prefered Fruits'] = df['Prefered Fruits'].str.replace(r'Custard apple\(सीताफल\)', 'Custard apple', regex=True)
df['Prefered Fruits'] = df['Prefered Fruits'].str.replace(r'Guava\(पेरु\)', 'Guava', regex=True)

In [13]:
df['Prefered Fruits'].unique()

array(['Apple', 'Banana', 'Orange', 'Mango', 'All seasonal fruits .',
       'Pineapple', 'Grape', 'Cheeries',
       'Apple, Banana, Lemon, Pomegranate',
       'Apple, Banana, Orange, Lemon, Pomegranate, Guava, Custard apple, ',
       'Apple, Banana, Orange, Pomegranate, Guava, Custard apple, Sapodilla,',
       'Apple, Banana, Orange, Lemon, Pomegranate, Guava',
       'Apple, Banana, Lemon, Guava',
       'Apple, Banana, Orange, Lemon, Pomegranate, Guava, Custard apple',
       'Banana, Lemon', 'Apple, Banana, Lemon, Guava, Kiwi, strawberry ',
       'Apple, Banana, Orange, Pomegranate',
       'Apple, Banana, Orange, Lemon, Pomegranate, Custard apple',
       'Orange, Pomegranate, Custard apple',
       'Lemon, Pomegranate, Guava, Custard apple',
       'Apple, Banana, Orange, Lemon, Pomegranate',
       'Orange, Lemon, Pomegranate', 'Apple, Banana, Orange, Lemon',
       'Orange, Pomegranate, Guava', 'Banana, Pomegranate, Custard apple',
       'Orange, Lemon, Guava',
       'Apple, Banana, Orange, Guava, Custard apple',
       'Banana, Orange, Lemon',
       'Orange, Lemon, Pomegranate, Guava, Custard apple', 'Pomegranate',
       'Apple, Banana, Orange', 'Banana, Orange, Lemon, Pomegranate',
       'Apple, Orange, Pomegranate, Custard apple',
       'Lemon, Pomegranate, Custard apple', 'Banana, Orange',
       'Orange, Lemon, Pomegranate, Strawbeery'], dtype=object)

In [14]:
df['Age'] = df['Age'].astype('int')

In [15]:
df = df.drop(['Timestamp','Email Address','Your Name'],axis = 1)

In [16]:
df.head()

,Age,Shopping Frequency,Do you prefer shopping online or in-store?,Prefered Fruits,Prefered vegetables,Budget,Are you interested in healthier food options?,Health Goals,Do you have preferred brands for certain products?,Payment Mode,Allergy
0,18,Once a week,Online,Apple,Carrots,200,Yes,muscle gain,Yes,Credit Card,NaN
1,18,Once a week,in-store,Banana,Broccoli,100,Yes,muscle gain,No,Mobile Wallet,NaN
2,18,twice a month,Online,Orange,Carrots,1000,Yes,Weight loss,Yes,Mobile Wallet,NaN
3,18,twice a month,Online,Apple,Carrots,1000,Yes,Weight loss,Yes,Cash,NaN
4,18,Once a week,in-store,Mango,Green vegetable,50,Yes,Maintain current health,Sometimes,Mobile Wallet,NaN

In [17]:
df['Prefered Food'] = df['Prefered Fruits'] + ' ' + df['Prefered vegetables']

In [18]:
df.head()

,Age,Shopping Frequency,Do you prefer shopping online or in-store?,Prefered Fruits,Prefered vegetables,Budget,Are you interested in healthier food options?,Health Goals,Do you have preferred brands for certain products?,Payment Mode,Allergy,Prefered Food
0,18,Once a week,Online,Apple,Carrots,200,Yes,muscle gain,Yes,Credit Card,NaN,Apple Carrots
1,18,Once a week,in-store,Banana,Broccoli,100,Yes,muscle gain,No,Mobile Wallet,NaN,Banana Broccoli
2,18,twice a month,Online,Orange,Carrots,1000,Yes,Weight loss,Yes,Mobile Wallet,NaN,Orange Carrots
3,18,twice a month,Online,Apple,Carrots,1000,Yes,Weight loss,Yes,Cash,NaN,Apple Carrots
4,18,Once a week,in-store,Mango,Green vegetable,50,Yes,Maintain current health,Sometimes,Mobile Wallet,NaN,Mango Green vegetable

In [19]:
new_df = df[['Health Goals','Prefered Food']]

In [20]:
new_df.head()

              Health Goals           Prefered Food
0              muscle gain           Apple Carrots
1              muscle gain         Banana Broccoli
2              Weight loss          Orange Carrots
3              Weight loss           Apple Carrots
4  Maintain current health  Mango Green vegetable

In [21]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [22]:
import nltk

In [23]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (3.8.1)
Requirement already satisfied: click in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from nltk) (2023.12.25)
Requirement already satisfied: tqdm in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from nltk) (4.66.1)
Requirement already satisfied: colorama in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from click->nltk) (0.4.6)

In [24]:
new_df['Prefered Food']=new_df['Prefered Food'].apply(lambda x : x.lower())

C:\Users\HP\AppData\Local\Temp\ipykernel_8524\391918178.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Prefered Food']=new_df['Prefered Food'].apply(lambda x : x.lower())

In [25]:
df.head()

,Age,Shopping Frequency,Do you prefer shopping online or in-store?,Prefered Fruits,Prefered vegetables,Budget,Are you interested in healthier food options?,Health Goals,Do you have preferred brands for certain products?,Payment Mode,Allergy,Prefered Food
0,18,Once a week,Online,Apple,Carrots,200,Yes,muscle gain,Yes,Credit Card,NaN,Apple Carrots
1,18,Once a week,in-store,Banana,Broccoli,100,Yes,muscle gain,No,Mobile Wallet,NaN,Banana Broccoli
2,18,twice a month,Online,Orange,Carrots,1000,Yes,Weight loss,Yes,Mobile Wallet,NaN,Orange Carrots
3,18,twice a month,Online,Apple,Carrots,1000,Yes,Weight loss,Yes,Cash,NaN,Apple Carrots
4,18,Once a week,in-store,Mango,Green vegetable,50,Yes,Maintain current health,Sometimes,Mobile Wallet,NaN,Mango Green vegetable

In [26]:
new_df = new_df.rename({'Prefered Food':'Prefered_Food'},axis = 1)

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

In [28]:
cv=CountVectorizer(max_features=5000,stop_words='english')

In [30]:
vectors=cv.fit_transform(new_df['Prefered_Food']).toarray()

In [31]:
vectors[0]

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [32]:
from sklearn.metrics.pairwise import cosine_similarity

In [33]:
similarity=cosine_similarity(vectors)

In [34]:
similarity[0].shape

(52,)

In [39]:
def recommend(health_goals):
    food_index=new_df[new_df['Health Goals']==health_goals].index[0]
    distances=similarity[food_index]
    food_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in food_list:
        print(new_df.iloc[i[0]].Prefered_Food)

In [40]:
recommend('muscle gain')

apple carrots
apple carrots
apple, orange, pomegranate, custard apple spinach, carrots, potato
apple, banana, orange, guava, custard apple broccoli, spinach, carrots
apple, banana, orange, lemon, pomegranate, custard apple carrots, potato, cucumber

In [48]:
from collections import Counter

def recommend(health_goals):
    food_index = new_df[new_df['Health Goals'] == health_goals].index[0]
    distances = similarity[food_index]
    food_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    preferred_foods = []

    for i in food_list:
        preferred_foods.extend(new_df.iloc[i[0]].Prefered_Food.split(', '))

    # Count the occurrences of each food
    food_counts = Counter(preferred_foods)

    # Print the top 3 most occurring foods
    top_3_foods = food_counts.most_common(3)

    for food, count in top_3_foods:
        print(food)

In [49]:
# Example usage
health_goal = 'Maintain current health'
recommend(health_goal)

apple carrots
mango bhendi
banana broccoli

In [52]:
import pickle
pickle.dump(new_df.to_dict(),open('food_dict.pkl','wb'))

In [53]:
pickle.dump(similarity,open('similarity.pkl','wb'))